[Junctions]
scns=J007_L03_01_X
#J007_L02_01_X,J007_L03_01_X,J007_L04_01_X
#,J007_L03_01_X,J007_L04_01_X
#J007_L02_01_X,J007_L03_01_X,J007_L04_01_X

[J007_L01_01_X]
stream=/home/abhishek/Downloads/dahod_videos1/Padav_L04.mp4


[J007_L02_01_X]
stream=/home/abhishek/Downloads/Out gate 730to 805.mp4


[J007_L03_01_X]
stream=/mnt/c/Documents and Settings/MANJU/Downloads/output1.mp4


[J007_L04_01_X]
stream=/home/abhishek/Downloads/dahod_videos1/Godha Gadi-From post office.mp4


[video_debug]
flag=True

[zone_config]
config=/mnt/c/Documents and Settings/MANJU/Downloads/nayanam-gui/nayanam-gui/flask_app/configfile.ini

[video_results]
pathnames=test1_result.mp4,test2_result.mp4,test3_result.mp4,test4_result.mp4

[nayanam_gui]
host=192.168.0.28
port=88

[classes]
id=0,1,2,3,4,5,6

[class_name]
custom_names = {0: 'person', 1: '3w', 2: 'car', 3: 'lmv', 4: 'hmv', 5: 'mav', 6: 'person'}

[frame_speed]
fps=8

[method]
logic = Y

[data_transport]
transport = REDIS

[api]
api_url = http://192.168.1.6:9893/iatcc

[count_publish]
publish = "detector"

[yolo_pt]
pt = /mnt/c/Documents and Settings/MANJU/Downloads/yolo_model/yolo_model/combined_best.pt

[yolo_engine]
engine = /home/abhishek/Downloads/engine_model/dahod_best.engine

[yolo_openvino]
openvino = /mnt/c/Documents and Settings/MANJU/Downloads/yolov9_finetuned_openvino_model/yolov9_finetuned_openvino_model/

[yolo_ncnn]
ncnn = /home/abhishek/Downloads/ncnn_model/dahod_best_ncnn_model/

[models]
model_id=3
device=cpu
